default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  prepared_statements: false

development:
  <<: *default
  database: school_development

test:
  <<: *default
  database: school_test

staging:
  <<: *default
  database: school_staging

production:
  <<: *default
  database: school_production

